USE `hackathon_bbva`;

CREATE TABLE `catalogo_giros` (
    `NU_AFILIACION` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `CD_GIRO` INT(11) NOT NULL,
    `NB_GIRO` VARCHAR(100) NOT NULL,
    `NB_SUBGIRO` VARCHAR(100) NOT NULL
);
CREATE TABLE `transacciones_cliente` (
    `NU_CTE_COD` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `FH_CORTE` DATE NOT NULL,
    `FH_OPERACION` DATE NOT NULL,
    `NU_AFILIACION` INT(11) NOT NULL,
    `TIPO_TARJETA` VARCHAR(100) NOT NULL,
    `IM_TRANSACCION` DECIMAL(10, 2) NOT NULL
);
CREATE TABLE `descripcion_cliente` (
    `NU_CTE_COD` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `EDAD` INT(11) NOT NULL,
    `CD_ESTADO` INT(11) NOT NULL,
    `CD_POSTAL` INT(11) NOT NULL,
    `CD_SEXO` INT(11) NOT NULL
);
ALTER TABLE `transacciones_cliente`
ADD FOREIGN KEY (`NU_AFILIACION`) REFERENCES `catalogo_giros` (`NU_AFILICACION`);
ALTER TABLE `descripcion_cliente`
ADD FOREIGN KEY (`NU_CTE_COD`) REFERENCES `transacciones_cliente` (`NU_CTE_COD`);